version: '3.8'

services:
  bot:
    build: .
    container_name: steam_train_bot
    restart: unless-stopped
    env_file:
      - .env
    # Если файл .env не существует, можно использовать env:
    # env_file:
    #   - env

